name: sri_bmi
description: "A new bmi project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+2

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

 
  fonts:
    - family: RubikBold
      fonts:
        - asset: fonts/Rubik-Bold.ttf
        
    - family: RubikRegular
      fonts:
        - asset: fonts/Rubik-Regular.ttf
  
